services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - noteboards

  backend:
    image: ghcr.io/danieljimenezrivares/mern-docker-deployment-backend:main
    container_name: backend
    restart: unless-stopped
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/noteboards?authSource=admin"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - noteboards

  frontend:
    image: ghcr.io/danieljimenezrivares/mern-docker-deployment-frontend:main
    container_name: frontend
    restart: unless-stopped
    environment:
      API_BACKEND: "http://backend:4000"
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - noteboards

volumes:
  mongo_data:

networks:
  noteboards: